### ISSUE TITLE
Allow multiple Identifier generators

### ISSUE THREAD

**Issue by nikonovd** [flosse/json-file-store#10]
Currently the id is always generated using a v4 uuid:

https://github.com/flosse/json-file-store/blob/master/src/Store.coffee#L82

It would be more flexible if it would be allowed to use different id generators, e.g. incremental numerical ids.

For instance, there should be an option key that allows to define the way the id is generated, e.g. 'uuid', 'numerical', or maybe we could pass a function that serves as a generator.

**Comment by flosse** [comment]
Feel free to open a PR :)

**Comment by flosse** [comment]
> [...] or maybe we could pass a function that serves as a generator.

This is the way I'd go!
