### ISSUE TITLE
canWrite denies access for root

### ISSUE THREAD

**Issue by erikbrannstrom** [flosse/json-file-store#12]
Hey!

I came across an issue when using BotKit, which in turns use this package. I was running a script as root (it's not running as root anymore FYI) when I notices that it could not write to the store, which was created by my real user. After some debugging, I traced it to the `canWrite` function in this package.

The function only checks if the file owner and permissions matches the current user, which doesn't cover the case of root since that user should have access even though it doesn't own the file.

I don't really get CoffeeScript, but I think a more appropriate way to do this is either use `fs.access(file, fs.constants.W_OK)` or the recommended way of simply trying to write and check for an error at that time.

Best regards,
Erik

**Comment by flosse** [comment]
Thanks for reporting!

> I don't really get CoffeeScript, but I think a more appropriate way to do this is either use `fs.access(file, fs.constants.W_OK)` or the recommended way of simply trying to write and check for an error at that time.

I like the latter :)

**Comment by flosse** [comment]
@erikbrannstrom I just merged the JS branch into master, so there is no coffee-script anymore. If your like you can create a PR :)

**Comment by erikbrannstrom** [comment]
Done! :)
