### ISSUE TITLE
saving an object with an undefined value will not save the object

### ISSUE THREAD

**Issue by Mosho1** [flosse/json-file-store#16]
```
const test = new Store('.test');
test.save('test', {x: undefined}) // doesn't work
test.save('test', {x: 'x'}) // works
```

**Comment by flosse** [comment]
Thanks for this bug report!

**Comment by flosse** [comment]
Internally JFS uses `JSON.stringify` that eliminates undefined values. Using `null` works great ;-)
What do you think would be a proper solution? Is that current behavior a bug or a feature?

**Comment by flosse** [comment]
...I just wrote a test and it works :-\ So it isn't a bug, is it?

**Comment by flosse** [comment]
I think we can close it. Feel free to reopen if needed.
