### ISSUE TITLE
both save and delete will not check existence of the record

### ISSUE THREAD

**Issue by windmaomao** [flosse/json-file-store#6]
so i need to wrap it with get() first. It'll be great if the library can take care for me, so that i can do 

        db.delete(id, function(err) {
            console.log(err);
            if (err) {
                next(err);
            } else {
                res.json({status: "success"});
            }
        });

instead of 

        db.get(id, function(err, item) {
            if (err) {
                next(err);
            } else {
                db.save(id, item, function(err) {
                    if (err) {
                        next(err);
                    } else {
                        item = db.getSync(id);
                        res.json(_attach_id(item, id));
                    }
                });
            }
        });

**Comment by flosse** [comment]
does [this commit](https://github.com/flosse/json-file-store/commit/36df4d43708669b65e45195257d788f7449a9dfe) change anything?

**Comment by flosse** [comment]
please reopen if it's not the case
