### ISSUE TITLE
In the documentation, file removed might be a typo.

### ISSUE THREAD

**Issue by windmaomao** [flosse/json-file-store#7]
// delete by ID
db.delete("myId", function(err){
  // the file data/myId.json was removed
});

probably it means that the record will be removed from that file :)

**Comment by flosse** [comment]
> probably it means that the record will be removed from that file :)

yes, as long as you're using a single file DB but in this case the file `myId.json` is only one record within the `data` directory that will be removed on a `delete` operation.
